"""Mini toolkit mapping dosage forms to inferred administration routes."""

from __future__ import annotations

import re
from typing import List, Optional, Tuple

FORM_TO_ROUTE = {
    "tablet": "oral",
    "tab": "oral",
    "tabs": "oral",
    "chewing gum": "oral",
    "capsule": "oral",
    "cap": "oral",
    "caps": "oral",
    "syrup": "oral",
    "syrups": "oral",
    "suspension": "oral",
    "suspensions": "oral",
    "solution": "oral",
    "solutions": "oral",
    "sachet": "oral",
    "granule": "oral",
    "granules": "oral",
    "lozenge": "oral",
    "mouthwash": "oral",
    "drops": "oral",
    "oral drops": "oral",
    "drop": "ophthalmic",
    "eye drop": "ophthalmic",
    "ear drop": "otic",
    "eye drops": "ophthalmic",
    "ear drops": "otic",
    "nasal drops": "nasal",
    "cream": "topical",
    "ointment": "topical",
    "gel": "topical",
    "lotion": "topical",
    "soap": "topical",
    "shampoo": "topical",
    "wash": "topical",
    "patch": "transdermal",
    "inhaler": "inhalation",
    "nebule": "inhalation",
    "neb": "inhalation",
    "inhal.aerosol": "inhalation",
    "inhal.powder": "inhalation",
    "inhal.solution": "inhalation",
    "oral aerosol": "inhalation",
    "ampoule": "intravenous",
    "amp": "intravenous",
    "ampul": "intravenous",
    "ampule": "intravenous",
    "vial": "intravenous",
    "vl": "intravenous",
    "inj": "intravenous",
    "injection": "intravenous",
    "suppository": "rectal",
    "ovule": "vaginal",
    "ovules": "vaginal",
    "mdi": "inhalation",
    "dpi": "inhalation",
    "metered dose inhaler": "inhalation",
    "dry powder inhaler": "inhalation",
    "spray": "nasal",
    "nasal spray": "nasal",
    "susp": "oral",
    "soln": "oral",
    "syr": "oral",
    "td": "transdermal",
    "supp": "rectal",
    "instill.solution": "ophthalmic",
    "lamella": "ophthalmic",
    "implant": "subcutaneous",
    "s.c. implant": "subcutaneous",
}

FORM_WORDS = sorted(set(FORM_TO_ROUTE.keys()), key=len, reverse=True)

ROUTE_ALIASES = {
    "po": "oral",
    "per orem": "oral",
    "by mouth": "oral",
    "iv": "intravenous",
    "intravenous": "intravenous",
    "im": "intramuscular",
    "intramuscular": "intramuscular",
    "sc": "subcutaneous",
    "subcut": "subcutaneous",
    "subcutaneous": "subcutaneous",
    "sl": "sublingual",
    "sublingual": "sublingual",
    "bucc": "buccal",
    "buccal": "buccal",
    "topical": "topical",
    "cutaneous": "topical",
    "dermal": "transdermal",
    "oph": "ophthalmic",
    "eye": "ophthalmic",
    "ophthalmic": "ophthalmic",
    "otic": "otic",
    "ear": "otic",
    "inh": "inhalation",
    "neb": "inhalation",
    "inhalation": "inhalation",
    "rectal": "rectal",
    "vaginal": "vaginal",
    "intrathecal": "intrathecal",
    "nasal": "nasal",
    "per os": "oral",
    "td": "transdermal",
    "transdermal": "transdermal",
    "intradermal": "intradermal",
    "id": "intradermal",
    "subdermal": "subcutaneous",
    "per rectum": "rectal",
    "pr": "rectal",
    "per vaginam": "vaginal",
    "pv": "vaginal",
    "per nasal": "nasal",
    "intranasal": "nasal",
    "inhaler": "inhalation",
}


def parse_form_from_text(norm_text: str) -> Optional[str]:
    """Return the first dosage form keyword found in the normalized text."""
    for form in FORM_WORDS:
        if re.search(rf"\b{re.escape(form)}\b", norm_text):
            return form
    return None
